# Generated by Django 5.1.5 on 2025-01-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="word_count",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
