# Generated by Django 5.1.5 on 2025-01-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_tour_word_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="comment",
        ),
    ]
