# Generated by Django 5.1.5 on 2025-01-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_tour_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tour",
            name="word_count",
            field=models.IntegerField(blank=True, default=""),
        ),
    ]
