# Generated by Django 5.1.5 on 2025-01-28 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_tour_comment_alter_tour_word_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tour",
            name="word_count",
        ),
    ]
